/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// On / OFF LED by Switch

#include <stdint.h>
#include <stdio.h>

#include "LED.h"
#include "SWITCH.h"
#include "Pattern.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	switch_init(SWITCH_PIN);

	led_init(LED_GREEN);
	led_init(LED_ORANGE);
	led_init(LED_RED);
	led_init(LED_BLUE);

    uint8_t pattern = 0;
    uint8_t prev = 0;
    uint8_t curr;

    while(1)
    {
        curr = (GPIOA->IDR & BV(0)) ? 1 : 0;

        if(curr == 1 && prev == 0)
        {
            pattern++;
            if(pattern > 5)
                pattern = 0;

            DelayMs(200);
        }

        prev = curr;

        run_pattern(pattern);   // 🔥 key line
    }

        prev = curr;

}

